### ISSUE TITLE
Entities end index error

### ISSUE THREAD

**Issue by Liangtaiwan** [Yoctol/uttut#70]
Entities end index should +1.

**Comment by stegben** [comment]
Could you provide any example or error message?

**Comment by Liangtaiwan** [comment]
@stegben 

The following is the examples, both of the entities should be technique.
However, we get techniqu,

<Datum 請問你們是用technique深度學習嗎 [14] with entities: [<Entity 3: techniqu at 6 - 14, with replacements: framework, ai, 自然語言技術, 深度學習, Machine learning, API, open source, 自然語意理解, 架構, 自然語意探勘, api, Deep learning, 開源, 語意理解, 語意分析, deep learning, 機器學習, Bottender, bottender, 人工智能, 自然語言處理, 語意辨識, nlu, NLU, 自然語意分析, 框架, AI , machine learning, 人工智慧, 自然語意, Framework, framwork>]>

<Datum 機器人technique程度到哪 [14] with entities: [<Entity 3: techniqu at 3 - 11, with replacements: framework, ai, 自然語言技術, 深度學習, Machine learning, API, open source, 自然語意理解, 架構, 自然語意探勘, api, Deep learning, 開源, 語意理解, 語意分析, deep learning, 機器學習, Bottender, bottender, 人工智能, 自然語言處理, 語意辨識, nlu, NLU, 自然語意分析, 框架, AI , machine learning, 人工智慧, 自然語意, Framework, framwork>]>

**Comment by SoluMilken** [comment]
Where did you get this data?
